### ISSUE TITLE
how to get the multi-view images

### ISSUE THREAD

**Issue by wefwefWEF2** [3dlg-hcvc/DuoduoCLIP#1]
Thanks for your great work!

May I ask how to get the multi-view images and embeddings of the point cloud? Could you please release the code?

**Comment by hanhung** [comment]
Hi, we will be releasing the full training code in the coming weeks along with the multi-view images embeddings and text embeddings.

**Comment by ApocalypsezZ** [comment]
I got the same question about view selection.

**Comment by hanhung** [comment]
Hello, we have now released the instructions for obtaining the multi-view images as well as the embeddings for the Four datasets. The embeddings were obtained by running the multi-view images and text captions from [OpenShape](https://github.com/Colin97/OpenShape_code) through the CLIP teacher. Note that our method does not involve point clouds.

Regarding the view selection, we use the rendering code from [Zero123](https://github.com/cvlab-columbia/zero123/blob/main/objaverse-rendering/scripts/blender_script.py#L119). Here the views are drawn uniformly from a sphere for camera positions with varying radius. We follow this view selection strategy to ensure the robustness of our method to varying viewpoints.
