### ISSUE TITLE
Question about is_multi_view configuration in training

### ISSUE THREAD

**Issue by sumuru789** [3dlg-hcvc/DuoduoCLIP#3]
Hello,

First of all, I want to say that I am very interested in your work. I have been exploring your code and I noticed that in the configuration, the is_multi_view parameter is set to False by default:
`is_multi_view: Optional[bool] = False`
Could you please clarify whether this parameter was set to False or True during your training process?

Thank you for your help!

**Comment by hanhung** [comment]
Hi,

I think you are referring to ```line 56``` in [src/custom_clip/model.py](https://github.com/3dlg-hcvc/DuoduoCLIP/blob/main/src/custom_clip/model.py#L56). Here the default is indeed False. However, in the ```get_model``` function in [src/model/duoduoclip.py](https://github.com/3dlg-hcvc/DuoduoCLIP/blob/main/src/model/duoduoclip.py#L16) we create the multi-view CLIP model with configs in [src/custom_clip/model_configs/ViT-B-32-MV.json](https://github.com/3dlg-hcvc/DuoduoCLIP/blob/main/src/custom_clip/model_configs/ViT-B-32-MV.json#L8) where the parameter is set to True ```"is_multi_view": true```.

Hope that helps!

**Comment by sumuru789** [comment]
Thank you for your prompt response and clarification. I appreciate your help!
